services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: ${APP_NAME}
    env_file:
      - ".env"
    volumes:
      - ./src:./app_workdir/src
    ports:
      - "${APP_HOST}:${APP_PORT}:${APP_PORT}"