FROM python:3.13-alpine

WORKDIR /app_workdir

RUN apk add --no-cache \
    gcc \
    musl-dev \
    linux-headers

COPY --from=ghcr.io/astral-sh/uv:0.6.14 /uv /uvx /bin/

COPY . .
RUN uv sync --frozen --no-cache

EXPOSE ${APP_PORT}

ENTRYPOINT [ "/app_workdir/.venv/bin/fastapi", "dev", "src" ]
CMD [ "--host", "0.0.0.0", "--port", "8000" ]