services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: ${APP_NAME}
    env_file:
      - ".env"
    volumes:
      - ./src:/app_workdir/src
    ports:
      - "${APP_HOST}:${APP_PORT}:${APP_PORT}"
    depends_on:
      redis-ddup:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
  
  redis-ddup:
    image: redis:7.4.2-alpine
    container_name: ${REDIS_DDUP_HOST}
    command: 
      - redis-server 
      - --maxmemory 2gb 
      - --maxmemory-policy volatile-lfu 
      - --save "" 
      - --appendonly no 
      - --activerehashing yes 
      - --lazyfree-lazy-eviction yes
    env_file:
      - ".env"
    ports:
      - "6379:${REDIS_PORT}"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 10s

  redis-queue:
    image: redis:7.4.2-alpine
    container_name: ${REDIS_QUEUE_HOST}
    command: 
      - redis-server 
      - --maxmemory 2gb 
      - --maxmemory-policy volatile-lfu 
      - --save "" 
      - --appendonly no 
      - --activerehashing yes 
      - --lazyfree-lazy-eviction yes
    env_file:
      - ".env"
    ports:
      - "6380:${REDIS_PORT}"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 10s

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: 
      - worker 
      - --loglevel=info 
      - --concurrency=1000
      - --prefetch-multiplier=0
      - --optimization=fair
    env_file:
      - ".env"
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '1.5'
          memory: 1G
    depends_on:
      redis-ddup:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
      app:
        condition: service_started

  locust:
    image: locustio/locust:2.34.1
    container_name: ${TESTAPP_HOST}
    env_file:
      - ".env"
    ports:
      - "${TESTAPP_PORT}:${TESTAPP_PORT}"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host=http://${APP_NAME}:${APP_PORT}

# Uncomment to keep data after restart
# volumes:
#   redis_data_ddup_test:
#   redis_data_queue_test: