FROM python:3.13-alpine

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PATH="/app_workdir/.venv/bin:$PATH"

WORKDIR /app_workdir

RUN apk add --no-cache \
    gcc \
    musl-dev \
    linux-headers \
    redis

COPY --from=ghcr.io/astral-sh/uv:0.6.14 /uv /uvx /bin/

COPY pyproject.toml uv.lock ./
RUN uv venv .venv && \
    uv sync --frozen --group celery --no-cache
COPY . .

ENTRYPOINT [ "celery", "-A", "src.worker.app" ]